version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: _go.dockerfile
      target: builder
    image: go-image
    container_name: email-dispatcher-go
    volumes:
      - .:/go/src/app

networks:
  default:
    external: true
    name: micro-service-user_api-go-web

volumes:
  api-web:
    driver: local
